: SAVESYSTEM
  $FFFF      $600 !
  ORIGIN 8 - $602 !
  HERE       $604 !
  FILE" W/O OPEN-FILE DROP 
  DUP $600 6 ROT 
  WRITE-FILE ( save header ) DROP
  DUP ORIGIN 8 - HERE 
      ORIGIN 8 - - 1+ ROT 
  WRITE-FILE DROP
  $02E0      $602 !
  $02E1      $604 !
  ORIGIN 8 - $606 !
  DUP $602 6 ROT 
  WRITE-FILE DROP 
  CLOSE-FILE DROP ;

' SAVESYSTEM ALIAS SAVE-SYSTEM

